name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: |
          docker build -t myapp .
          docker run --rm myapp 