name: Build / Test

on:
  push:
    branches:
      - main
jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t myapp .
      
      - name: Test
        run: docker run --rm myapp 